python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --queue_choice_strategy least_items --queue_jockeying_strategy no_jockeying --customer_standard_deviation_coefficient 0 --name validazione_1 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --queue_choice_strategy least_people --queue_jockeying_strategy no_jockeying --customer_standard_deviation_coefficient 0 --name validazione_2 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --queue_choice_strategy least_waiting_time_service_implied --queue_jockeying_strategy no_jockeying --customer_standard_deviation_coefficient 0 --name validazione_3 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --queue_choice_strategy least_waiting_power_implied --queue_jockeying_strategy no_jockeying --customer_standard_deviation_coefficient 0 --name validazione_4 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_items --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0 --name coda1_jockey1 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_items --queue_jockeying_strategy least_people --customer_standard_deviation_coefficient 0 --name coda1_jockey2 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_people --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0 --name coda2_jockey1 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_people 3 --probability_of_jockeying 0.5 --queue_choice_strategy least_people --queue_jockeying_strategy least_people --customer_standard_deviation_coefficient 0 --name coda2_jockey2 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_waiting_time_service_implied --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0 --name coda3_jockey1 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_people 3 --probability_of_jockeying 0.5 --queue_choice_strategy least_waiting_time_service_implied --queue_jockeying_strategy least_people --customer_standard_deviation_coefficient 0 --name coda3_jockey2 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_waiting_power_implied --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0 --name coda4_jockey1 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_people 3 --probability_of_jockeying 0.5 --queue_choice_strategy least_waiting_power_implied --queue_jockeying_strategy least_people --customer_standard_deviation_coefficient 0 --name coda4_jockey2 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 10 --number_cash_desk_self_service_groups 1 --shared_queue True --queue_choice_strategy least_items --queue_jockeying_strategy no_jockeying --customer_standard_deviation_coefficient 0 --name codacondivisa_10 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 5 --number_cash_desk_self_service_groups 1 --shared_queue True --queue_choice_strategy least_items --queue_jockeying_strategy no_jockeying --customer_standard_deviation_coefficient 0 --name codacondivisa_5 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 6 --number_cash_desk_self_service_groups 1 --shared_queue True --queue_choice_strategy least_items --queue_jockeying_strategy no_jockeying --customer_standard_deviation_coefficient 0 --name codacondivisa_6 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 7 --number_cash_desk_self_service_groups 1 --shared_queue True --queue_choice_strategy least_items --queue_jockeying_strategy no_jockeying --customer_standard_deviation_coefficient 0 --name codacondivisa_7 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 8 --number_cash_desk_self_service_groups 1 --shared_queue True --queue_choice_strategy least_items --queue_jockeying_strategy no_jockeying --customer_standard_deviation_coefficient 0 --name codacondivisa_8 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 5 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_items --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0 --name coda1_jockey1_5 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 6 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_items --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0 --name coda1_jockey1_6 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 7 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_items --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0 --name coda1_jockey1_7 &
python main.py --number_cash_desk_self_scan 0 --number_cash_desk 8 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_items --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0 --name coda1_jockey1_8 &
python main.py --number_cash_desk_self_scan 7 --number_cash_desk 0 --number_cash_desk_self_service_groups 0 --shared_queue False --queue_choice_strategy least_items --queue_jockeying_strategy no_jockeying --customer_standard_deviation_coefficient 0 --self_scan_customer_percentage 1 --grid_height 70 --name self_scan &
python main.py --number_cash_desk_self_scan 5 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_items --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0.1 --self_scan_customer_percentage 0.1 --name prob_coda1_jockey1 &
python main.py --number_cash_desk_self_scan 5 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_people 3 --probability_of_jockeying 0.5 --queue_choice_strategy least_items --queue_jockeying_strategy least_people --customer_standard_deviation_coefficient 0.1 --self_scan_customer_percentage 0.1 --name prob_coda1_jockey2 &
python main.py --number_cash_desk_self_scan 5 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_people --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0.1 --self_scan_customer_percentage 0.1 --name prob_coda2_jockey1 &
python main.py --number_cash_desk_self_scan 5 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_people 3 --probability_of_jockeying 0.5 --queue_choice_strategy least_people --queue_jockeying_strategy least_people --customer_standard_deviation_coefficient 0.1 --self_scan_customer_percentage 0.1 --name prob_coda2_jockey2 &
python main.py --number_cash_desk_self_scan 5 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_waiting_time_service_implied --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0.1 --self_scan_customer_percentage 0.1 --name prob_coda3_jockey1 &
python main.py --number_cash_desk_self_scan 5 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_people 3 --probability_of_jockeying 0.5 --queue_choice_strategy least_waiting_time_service_implied --queue_jockeying_strategy least_people --customer_standard_deviation_coefficient 0.1 --self_scan_customer_percentage 0.1 --name prob_coda3_jockey2 &
python main.py --number_cash_desk_self_scan 5 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_items 15 --probability_of_jockeying 0.5 --queue_choice_strategy least_waiting_power_implied --queue_jockeying_strategy least_items --customer_standard_deviation_coefficient 0.1 --self_scan_customer_percentage 0.1 --name prob_coda4_jockey1 &
python main.py --number_cash_desk_self_scan 5 --number_cash_desk 20 --number_cash_desk_self_service_groups 1 --shared_queue False --threshold_people 3 --probability_of_jockeying 0.5 --queue_choice_strategy least_waiting_power_implied --queue_jockeying_strategy least_people --customer_standard_deviation_coefficient 0.1 --self_scan_customer_percentage 0.1 --name prob_coda4_jockey2 &